ignore:
  - wiredb.go
  - (?s:example/[^\/]+\.go.*)\Z
  - ^doc.go.*
  - (?s:[^\/]+_test\.go.*)\Z
  - cmd/
  - server/


coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 5%
      vfs:
        target: 20% 